package driver;

import dao.RepayRequestDao;
import dao.UserDao;
import dao.UserTypeDao;
import model.RepayRequest;
import model.User;
import model.UserType;
import service.UserService;

public class Driver {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		

	//----------------------------------------------------------------------------------	
	//create new user to insert into table withput id ; id will be generated by database
	
//		UserDao userdao = new UserDao();
	//must create a type object first to link to user type table; so later we can get the type of user either employyee or manager; 
		//create usertype object first ; one for employee; one for manger then add to db; user type table should only have two rows ;
		//one for manger and one for employee
		//;then create usertype object with matching id and put in the user object and put in user table;
		//it should link the new created user to the one in user role table;
		//this is for test purpose
		
		//create employe type object
//	UserType usertype = new UserType("employee");
		
//		UserType usertype = new UserType("manager");
		
		//use usertype dao to add to usertype table
	//UserTypeDao usertypeDao = new UserTypeDao();
		
	//	usertypeDao.insert(usertype);
	
		
		
		//create user type with id from usertype table; this usertype row already in user type table
		
		
//	UserType usertypeManager = new UserType(19, "manager");
		

	//		UserType usertypeEmployee = new UserType(20, "employee");
		
//		parameters String firstname, String lastname, String password, UserType userTypeHolde
//	User user = new User("Moon", "Tran",  "123",   usertypeEmployee);
//		User user = new User("Sun", "Tran",  "789",   usertypeEmployee);

	
		//manger user
		
//	User user = new User("Hien", "Tran",  "1234",    usertypeManager);		
//	
//	
//	UserDao userdao = new UserDao();
//	userdao.insert(user);
//		
		//--------------------------------------------------------------------------------------
		//to create a new request using the user already exist in database
//		(int id, String firstname, String lastname, String username, String password)
//	User user = new User(13, "David",  "Tran",   "DavidTran5658", "4567");	
		// RepayRequest(int amount, String status, String description, User requestHolder)
//	RepayRequest repayRequest = new RepayRequest( 100, "pending","food", user);
//-------------------------------------------------------------------
	
		//must make a user type ofject  employee when insert a request in repay request table
		//or the foriegn key in user table will be null; then it will not point to user type employee
		//table
	
//		UserType usertypeEmployee = new UserType(20, "employee");
//	User user = new User(26, "Sun",  "Tran",   "SunTran2800", "789", usertypeEmployee);	
//	RepayRequest repayRequest = new RepayRequest( 1000, "pending","other", user);
//	RepayRequestDao repayRequestDao = new RepayRequestDao();
//	
//		
//		System.out.println(repayRequestDao.insert(repayRequest));
		

//-------------------------------------------------------------------	
//		
//		UserType usertypeEmployee = new UserType(20, "employee");
//	User user = new User(23, "Moon",  "Tran",   "MoonTran2157", "123", usertypeEmployee);	
//	RepayRequest repayRequest = new RepayRequest( 300, "pending","lodging", user);
//	RepayRequestDao repayRequestDao = new RepayRequestDao();
//	repayRequestDao.insert(repayRequest);

		 //-----------------------   
	    
//	   System.out.println(     repayRequestDao.getAllPendingRepayRequestForAnEmployee(14 )              );
//--------------------------------------------------------------------------------		
		
//these all for manager
//		get all approved and denied request for a specific employee
		
//		RepayRequestDao repayRequestDao = new RepayRequestDao();
		
	//	 System.out.println(  repayRequestDao.getAllApprovedAndDeniedRepayRequestForAnEmployee(26)                   )		;
		//----------------------------------------------------
		
		//get all request from all employee with condition pending status for manager  
		 
//		 System.out.println(  repayRequestDao.getAllPendingRepayRequestOfAllEmployees()                )		;
		 
		 
		 
		//get a specific repay request by repay request  id
		 
	//	 System.out.println(  repayRequestDao.getASpecificrequestById(30)         )		;
		 
		//get all repay  request of an employee ; take in id of employee; for manager  
		 
//		 System.out.println(  repayRequestDao.getAllRepayRequestsOfAnEmployee(26)         )		;
		 
		
		
//	//get a user by  username and  pass word ;will return a user object if found ; if no will return null ;for employee		
//		UserDao userdao = new UserDao();
//
//		 System.out.println(     userdao.getAuserByUsernameAndPassword("SunTran2800", "78")     )		;
		
		
//		//get all users for manager		
//		UserDao userdao = new UserDao();
//
//		 System.out.println(     userdao.getAllUsers()    )		;
		
// type of repay request LODGING, TRAVEL, FOOD, or OTHER
		
//		userdao.update(user);
//System.out.println(userdao.selectUser(1));	
		
		UserService userService =  new UserService();
		
		try {
			System.out.println(    userService.signin("SunTran2800", "789")    );		
		} catch (Exception e) {
		System.out.println(e.getMessage());	
		}
		
		
	}

}
